# Generated by Django 6.0.2 on 2026-02-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('dispatcher', 'Dispatcher'), ('safety_officer', 'Safety Officer'), ('analyst', 'Analyst'), ('driver', 'Driver')], default='dispatcher', max_length=20),
        ),
    ]
